### ISSUE TITLE
Unable to Set Temperature

### ISSUE THREAD

**Issue by d0nni3q84** [bwoodworth/hassio-addons#1]
Tab character causes error `/run.sh: line 193: ./set_temp 10.10.10.10 0 80.0: No such file or directory`. As a result, users are unable to change the Pool or Spa temperature.

**Code Reference**
https://github.com/bwoodworth/hassio-addons/blob/2e386d862825ebcecd4a5acf8ebf572491c417e4/pentair-screenlogic/run.sh#L185-L194

**Patch**

```
    ;;
    "pentair/heater/spa/temperature/set")
    if [ 1 ]; then
      ./set_temp $SCREENLOGICIP 1 "${MESSAGE}"
    fi
    ;;
    "pentair/heater/pool/temperature/set")
    if [ 1 ]; then
      ./set_temp $SCREENLOGICIP 0 "${MESSAGE}"
    fi
```

**Comment by bwoodworth** [comment]
Thanks, but I'm having a hard time figuring out what the difference is in your patch.

**Comment by bwoodworth** [comment]
Oh, I see.  Its the tabs.  I tried removing the tabs, but I am still not able to get it to work.  Did you get it to work?

**Comment by d0nni3q84** [comment]
Yes, after removing the tabs and also the `..` characters which can be observed when editing `run.sh` with **vi**.

![unexpected_characters](https://user-images.githubusercontent.com/62199227/76717145-ce7a3d80-6700-11ea-9438-2bdfd7a1f708.png)

**Comment by bwoodworth** [comment]
Thanks!  Not sure how all those bad characters got in there, but it is working now.
