### ISSUE TITLE
Does not support screen logic passwords

### ISSUE THREAD

**Issue by resistr** [bwoodworth/hassio-addons#10]
Hi; 

The underlying library supports providing a password for the screen logic connection; but this wrapper for Home Assistant doesn't. 

Request is to add an optional configuration parameter for the screen logic password and modify the underlying code to use it. 

I have made what I think are the minimal amount of non-breaking changes in a fork and can create a PR; but wanted to start the dialog while I test the changes and ensure they do not break running without a password; but also enable the use of one if specified. 

Please let me know if you are open to modifications to the repo and/or any requirement you may have for PRs.

you may preview the changes here: https://github.com/resistr/hassio-addons/commit/6042b592274d2e78c80220a29d1b719af8a8d7ce and I'll create a PR after testing & and I hear back from someone.   

Thanks!

**Comment by bwoodworth** [comment]
Thanks!  Yes, I am open to other contributions.  Have you tested your changes if the ScreenLogic doesn't have a password set?

**Comment by resistr** [comment]
Perfect, sorry for the delay responding. I'll test as follows this weekend: 

- Remove SL password
- install your plugin
- verify can read properties and change settings
- Install my update (password still removed)
- re-verify reading properties and changing settings
- set SL password and configure plugin with password 
- re-verify reading properties and changing settings

Once all of that is complete and verified I'll raise a PR back to this repo with the changes. 

For reading and writing states I will be focusing on pool state (off, pool, spa), lights, and salt cell. 

Will that be sufficient or is there anything else I should look for when verifying?  The setup I have access to has a heater, but not an intellachem; so no matter what I can't test the chem state, but based on the changes if one connection works they all should. 

Also I already realized I missed the .sh file; I've made that change as well. But the PR would contain all of the changes post verification. 

Thanks!

**Comment by bwoodworth** [comment]
That sounds great.  If the initial connection works when starting up the addon then they should all work so don't worry about testing every possible case.

**Comment by resistr** [comment]
Ok tested as we discussed. Here is the PR (#11) that should close this issue. https://github.com/bwoodworth/hassio-addons/pull/11

Thanks!

**Comment by bwoodworth** [comment]
Thanks!  Merged in and created version 1.2
