### ISSUE TITLE
Decouple & Place on DockerHub

### ISSUE THREAD

**Issue by cbschuld** [bwoodworth/hassio-addons#15]
Hey Brian, thanks for your work here; I want to use it but I do not use HASSIO I use vanilla HA.  Curious if you have any heart burn if I decouple it and drop it on dockerhub?  The idea is then folks w/o HASSIO could execute that docker image and then use your YAML inside of vanilla HA. Happy to do it on a private repo but I suspect I may not be the only nerd not using HASSIO and want to use your work.
Thanks//cbs

**Comment by bwoodworth** [comment]
Yeah, I have no problem putting on docker hub. Thanks for your interest in it.

**Comment by cbschuld** [comment]
Hey Brian, thanks a bunch - all set and working - appreciate your work; you accelerated my efforts * 100

GH: https://github.com/cbschuld/pentair-screenlogic

DH: https://hub.docker.com/repository/docker/cbschuld/pentair-screenlogic

I am closing this!  Thanks again!
