### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by omayhemo** [bwoodworth/hassio-addons#21]
HASSOS, Supervised on a NUC, latest version

Failed to install add-on
The command '/bin/ash -o pipefail -c apk add npm jq mosquitto-clients && npm install node-screenlogic smart-buffer' returned a non-zero code: 1

**Comment by omayhemo** [comment]
I guess this add-on is dead?

**Comment by bwoodworth** [comment]
There is a new Pentair integration that replaced this add-on long ago

**Comment by omayhemo** [comment]
Thanks I see it now.
