### ISSUE TITLE
HomeKit climate fail

### ISSUE THREAD

**Issue by rjw2324** [bwoodworth/hassio-addons#3]
See: https://github.com/home-assistant/core/issues/35256

A recent update to HomeKit uncovered an issue with the climate for pool and spa.  Below is the recommended fix. 

mode_state_topic needs to send CURRENT_HVAC_HEAT ("heating") and CURRENT_HVAC_OFF ("off") instead of ON and OFF for it to work

**Comment by bwoodworth** [comment]
Ok, I think I see the issue. Just remove the action_topic from the config for your mqtt hvac device.  That is unnecessary.
