### ISSUE TITLE
Circuits Other than pool and spa report but do not respond to command topics

### ISSUE THREAD

**Issue by iannecj** [bwoodworth/hassio-addons#4]
The addon takes the earlier work over the finish line! thank you very much!  All is configured and I thought flawless until I entered some of my feature circuits into the switch yaml section and place on lovelace.

I was able to get their circuit number from the inital log output used when the addon startys up in hassio.

In short, these switches update their state when I command these pool feature circuits via the pentair screenlogic android app.  However, I cannot command them via that button.  The lightning bolt button then is actually only an indicator.  The pool circuit does work.

When I listen to those circuits' command topic I do see the button is sending an OFF....just as it does with pool circuit but still no control.

An issue in the code base?

**Comment by iannecj** [comment]
Think I see where it is but not really a software guy or github literate otherwise I would make the fix.
I notice at least one place there is a limit that would impact this for my setup...
hassio-addons/pentair-screenlogic/run.sh

There it seems to stop at circuit number......519...however I routinely have feature circuits in my i9 intellitouch assigned circuit numbers higher than this number.

Here is my add on log:


"id": 547,
"state": 0,
"colorSet": 0,
"colorPos": 0,
"colorStagger": 0,
"delay": 0
},
{
"id": 548,
"state": 0,
"colorSet": 0,
"colorPos": 0,
"colorStagger": 0,
"delay": 0
},
{
"id": 549,
"state": 0,
"colorSet": 0,
"colorPos": 0,
"colorStagger": 0,
"delay": 0
}
],
"pH": 0,
"orp": 0,
"saturation": 0,
"saltPPM": 0,
"pHTank": 0,
"orpTank": 0,
"alarms": 0
}
pool ok=1
pool active=false
pool temp=78
pool settemp=84
pool heatStatuse=0
pool heatStatuse=off
spa active=false
spa temp=101
spa settemp=101
spa heatStatuse=heat
salt ppm=0
pH=0
orp=0
saturation=0
air temp=71
freezeMode=0
alarms=0
Number of circuitArray Objects=20
calcium=0
cyanuric acid=0
alkalinity=0
salt cell installed=true
controller is in celsius=false
controllerId=100
pumpCircArray=65,105,106,0,0,0,0,0
Number of bodyArray Objects=20
bodyArray=
circuitId: 500
name: Spa
circuitId: 501
name: Pool Light
circuitId: 502
name: Spa Light
circuitId: 503
name: LOWER LIGHT
circuitId: 504
name: Air Blower
circuitId: 505
name: Pool
circuitId: 506
name: Swim Jets
circuitId: 507
name: Aux 6
circuitId: 508
name: Aux 7
circuitId: 509
name: Aux 8
circuitId: 540
name: EDGE 01
circuitId: 541
name: EDGE 02
circuitId: 542
name: SPA RAIN
circuitId: 543
name: POOL RAIN
circuitId: 544
name: BUBBLER
circuitId: 545
name: PARTY TIME
circuitId: 546
name: HIGH SPILL
circuitId: 547
name: CIRCULATION
circuitId: 548
name: HI SPILL VL
circuitId: 549
name: NIGHTLIGHT

**Comment by bwoodworth** [comment]
So your highest circuit ID is 549?  Let me take a look and see if this can be done dynamically

**Comment by iannecj** [comment]
Yes 549, thats what I was wondering too but I don't know this scripting.
Seems inefficient to not pass circuit number though.

If not, I would be happy to type this up to save you effort....maybe even
take the time to learn git

Thank your very much for this...and my whole family thanks you...they will
now be able to use the google home for voice control thanks to your addon.

**Comment by iannecj** [comment]
I notice a new release, not sure if I am setup right should this now support feature circuits up to 549?

**Comment by bwoodworth** [comment]
No, sorry.  That is not in this release.  It will be in the next one

**Comment by sarahmva** [comment]
build 121 has some improvements:

from the two valves I have, one now works 540. 547 does not.

  - platform: mqtt
    name: "Dek Jets"
    command_topic: pentair/circuit/540/command
    state_topic: pentair/circuit/540/state
    
  - platform: mqtt
    name: "Heat Valve"
    command_topic: pentair/circuit/547/command
    state_topic: pentair/circuit/547/state

**Comment by iannecj** [comment]
I can confirm all my higher circuit numbers can now be controlled thank you very much!  -Chris

**Comment by iannecj** [comment]
> I can confirm all my higher circuit numbers can now be controlled thank you very much! -Chris

@bwoodworth I had just forked this and was going to learn a bit of js in order to get my 3 pumps running.  Before I could get it figured out you had in there.  Cant thank you enough.... all my circuits, all my pumps.  

Not being a coder I havent been able to help as I want to but I wanted to contribute to your noble efforts.  I see a donate link on the http://www.opensourceautomation.com/ website.  Let me buy you dinner...thanks again!

-C

**Comment by bwoodworth** [comment]
@iannecj I'm glad it's working for you and thank you for wanting to donate. The OpenSourceAutomation project is kind of dead and actually don't know where the donate link goes. I should probably take that off my profile. I'll put something else on my profile if you feel so inclined, but definitely not necessary.

**Comment by iannecj** [comment]
Well i sent some money there before i got this note. Hope it makes its way
to you somehow. 25 bucks so not the end of the world.  Thanks again
