### ISSUE TITLE
Not sure what im doing wrong here.

### ISSUE THREAD

**Issue by ms30250** [bwoodworth/hassio-addons#6]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
 version=POOL: 5.2 Build 738.0 Rel
 pool ok=1
 pool active=false
 pool temp=78
 pool settemp=70
 pool heatStatuse=0
 pool heatStatuse=off
 spa active=false
 spa temp=77
 spa settemp=98
 spa heatStatuse=heat
 salt ppm=0
 pH=0
 orp=0
 saturation=0
 air temp=78
 freezeMode=0
 alarms=0
 Number of circuitArray Objects=14
 calcium=0
 cyanuric acid=0
 alkalinity=0
 salt cell installed=false
 controller is in celsius=false
 controllerId=100
 pumpCircArray=70,0,0,0,0,0,0,0
 Number of bodyArray Objects=14
 bodyArray=
   circuitId: 500
     name: Spa
   circuitId: 501
     name: Booster Pump
   circuitId: 502
     name: Air Blower
   circuitId: 503
     name: Light
   circuitId: 505
     name: Pool
   circuitId: 510
     name: Spillway
   circuitId: 511
     name: High Speed
   circuitId: 512
     name: Feature 3
   circuitId: 513
     name: Feature 4
   circuitId: 514
     name: Feature 5
   circuitId: 515
     name: Feature 6
   circuitId: 516
     name: Feature 7
   circuitId: 517
     name: Feature 8
   circuitId: 519
     name: AuxEx
Error: Connection refused
MQTT Client exited with non-zero status

**Comment by bwoodworth** [comment]
Looks like the connection to ScreenLogic is working, but the connection to the MQTT broker is not working.  Double check that you have the correct configuration and your MQTT broker is running.

**Comment by ms30250** [comment]
> Looks like the connection to ScreenLogic is working, but the connection to the MQTT broker is not working. Double check that you have the correct configuration and your MQTT broker is running.


i had my user and pass wrong, figured it out. I was also getting an error on the lights scenes part of the yaml config. I deleted it for now but it was complaining about the line where "script" starts?

**Comment by bwoodworth** [comment]
The configuration file is not meant to be a simple copy/paste, but rather an example of what you can add to your configuration.yaml file.  I would suggest reading the Home Assistant documentation on how to use scripts.

**Comment by ms30250** [comment]
> The configuration file is not meant to be a simple copy/paste, but rather an example of what you can add to your configuration.yaml file. I would suggest reading the Home Assistant documentation on how to use scripts.

Thank you!
