### ISSUE TITLE
Pump Watts

### ISSUE THREAD

**Issue by jefframsey0** [bwoodworth/hassio-addons#9]
Any chance you could add mqtt topic for the pump watts for the pentair-screenlogic project?

**Comment by bwoodworth** [comment]
looks like the next version of the nodejs library that this addon uses has pump info like watts so as soon as that is released I can add it to the addon.

**Comment by jefframsey0** [comment]
Thanks Brian! The addon has been working great by the way. I have moved all control and scheduling to home assistant this past week.

**Comment by sarahmva** [comment]
Would this include seeing pump rpm and flow (for varispeed / variflow pumps?) 
Also missing the ability to set the Chlorinator.

**Comment by bwoodworth** [comment]
Yes, it looks like it has rpm/gpm.  Hopefully @parnic releases the next version soon.

The chlorinator would be another issue. I don't have one so I haven't looked into adding that yet.

**Comment by parnic** [comment]
I can release a new one whenever. Will try to remember this evening.

**Comment by bwoodworth** [comment]
@parnic Thanks!  ...and thanks for your work on the library.  My addon has gotten a reasonable amount of traction and many people are using it.

**Comment by jefframsey0** [comment]
> Yes, it looks like it has rpm/gpm. Hopefully @parnic releases the next version soon.
> 
> The chlorinator would be another issue. I don't have one so I haven't looked into adding that yet.

@bwoodworth - I have a IntelliChlor IC40 on my pool if you need any data or someone to do a test. Just let me know how I can help.

**Comment by sarahmva** [comment]
Thanks @parnic and @bwoodworth ... Really great work.

I did look in the library and tried setting up HA according to the state values I found:
  - platform: mqtt
    name: "Pool Salt Status"
    state_topic: pentair/status/state

  - platform: mqtt
    name: "Pool Salt Level 1"
    state_topic: pentair/level1/state

  - platform: mqtt
    name: "Pool Salt Level 2"
    state_topic: pentair/level2/state

  - platform: mqtt
    name: "Pool Salt Superchlorinator"
    state_topic: pentair/level1/state    
    
  - platform: mqtt
    name: "Pool Salt ppm"
    unit_of_measurement: 'ppm'
    state_topic: pentair/saltppm/state    

I am just now realizing that some of these values would need to go into the switch section, not the sensor section (e.g. the salt levels)...

I will wait for the next release.

@bwoodworth : I also have an IC40 chlorinator and a Variflow pump which I can switch to a Varispeed pump. so if you need any data or want me to test something, just let me know :-)

**Comment by bwoodworth** [comment]
Since this is an unrelated issue I created a new one so as to not muddy up this one: https://github.com/bwoodworth/hassio-addons/issues/12

**Comment by bwoodworth** [comment]
Pump info added to version 1.21.  Please test

**Comment by sarahmva** [comment]
Thanks for the build.

I do see this in the logs:

TypeError: this.getPumpStatus is not a function
    at UnitConnection.<anonymous> (/node_modules/node-screenlogic/send_state_to_ha.js:52:10)
    at UnitConnection.emit (events.js:315:20)
    at UnitConnection.onClientMessage (/node_modules/node-screenlogic/index.js:287:14)
    at Socket.<anonymous> (/node_modules/node-screenlogic/index.js:148:15)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
/node_modules/node-screenlogic/send_state_to_ha.js:52
    this.getPumpStatus(0);

Am I missing some dependency?

**Comment by sarahmva** [comment]
looking through the code of node-screenlogic, it seems to me that somehow I di don't get the latest node-screenlogic when updating.

**Comment by iannecj** [comment]
> looking through the code of node-screenlogic, it seems to me that somehow I di don't get the latest node-screenlogic when updating.

I had the same problem.  I am using the hassio version for HA (supervised) with this as an addon.  I had to click rebuild on the add on page.  I later also restarted but dont know that was needed.  

The missing pump function message no longer in my addon logs.

**Comment by sarahmva** [comment]
> > looking through the code of node-screenlogic, it seems to me that somehow I di don't get the latest node-screenlogic when updating.
> 
> I had the same problem. I am using the hassio version for HA (supervised) with this as an addon. I had to click rebuild on the add on page. I later also restarted but dont know that was needed.
> 
> The missing pump function message no longer in my addon logs.

Thanks! Yes, that was it...

Now I just need to figure out how to set GPM or the salt level.

![image](https://user-images.githubusercontent.com/68161487/87686755-e3201e00-c752-11ea-924a-bd3630f7237c.png)

**Comment by bwoodworth** [comment]
There is currently no way to set any pump configuration.  The functionality is in the node library so it is possible to add.

To set the salt level you should be able to send a mqtt topic: pentair/salt/spa/set and pentair/salt/pool/set with a value 0-100.  Please test this out and let me know how it goes.  The library only has one function for setting both spa and pool at the same time so I'm not sure how it will work if we only do one at a time.  If it doesn't work I will have to figure out a different way to do it.

p.s. I love your lovelace setup.

**Comment by jefframsey0** [comment]
Working great, thanks again!
